### ISSUE TITLE
Hacker App > Portal + Livesite Theming

### ISSUE THREAD

**Issue by anneguo3** [nwplus/livesite#290]
Discover work to define the work required to make consistent theming across day-of hackathon portal and application portal

**Comment by panjenny0** [comment]
## Work required
This involves:
1. Consolidating the constant `DB_HACKATHON` and `selectedTheme` into one field, using `activeHackathon` set in CMS
  - `DB_HACKATHON` in [src/utility/Constants.js](https://github.com/nwplus/livesite/blob/69a1f3354f8041c61ec59784de149e7cd98dc1b8/src/utility/Constants.js#L3-L4) specifies which hackathon collection in the db is being used
  - `selectedTheme` in [src/theme/ThemeProvider.js](https://github.com/nwplus/livesite/blob/69a1f3354f8041c61ec59784de149e7cd98dc1b8/src/theme/ThemeProvider.js#L163) specifies the active hackathon theme
  - Currently, in order to change the theme of Livesite, we need to hard code `selectedTheme` and `DB_HACKATHON` 
  - What would be better: CMS has a field under [Livesite > Settings](https://admin.nwplus.io/Livesite/settings) that controls which hackathon is active - we should make use of this field to control both the theme and the hackathon collection in the db.
2. Adding theme support to a few minor application portal components

<hr/>

### Consolidating the constant `DB_HACKATHON` and `selectedTheme` into one field
Tickets
- Change `DB_HACKATHON` to use the `activeHackathon` field in firebase ([InternalWebsites > Livesite > `activeHackathon`](https://console.firebase.google.com/u/0/project/nwplus-ubc-dev/firestore/data/~2FInternalWebsites~2FLivesite)). Relevant file/change:  [src/utility/Constants.js](https://github.com/nwplus/livesite/blob/69a1f3354f8041c61ec59784de149e7cd98dc1b8/src/utility/Constants.js#L3-L4) 
- Support `selectedTheme` to dynamically set theme based on `DB_HACKATHON`. Relevant file/change: [src/theme/ThemeProvider.js](https://github.com/nwplus/livesite/blob/69a1f3354f8041c61ec59784de149e7cd98dc1b8/src/theme/ThemeProvider.js#L163)
<hr/>

### Adding theme support to a few minor application portal components
Currently, all components (input/button/background/progress/navbar/etc) except for a few already support theming.

#### Checklist of components that need to be updated to support theming (code change: a few lines each, all in `src/components`):

[XS] Application Dashboard > StatusContainer ([src/components/ApplicationDashboard.js](https://github.com/nwplus/livesite/blob/69a1f3354f8041c61ec59784de149e7cd98dc1b8/src/components/ApplicationDashboard.js#L60))
- Change [`p.theme.colors.applicationCard`](https://github.com/nwplus/livesite/blob/69a1f3354f8041c61ec59784de149e7cd98dc1b8/src/components/ApplicationDashboard.js#L66) in the theme [object](https://github.com/nwplus/livesite/blob/main/src/theme/ThemeProvider.js#L78)
- Screenshot (on /application): <img width="1680" alt="Screen Shot 2021-11-09 at 7 02 16 PM" src="https://user-images.githubusercontent.com/38872354/141041892-6343566c-8ae7-40f3-b0d2-9a3e1c429e97.png">
<img width="842" alt="Screen Shot 2021-11-09 at 7 33 10 PM" src="https://user-images.githubusercontent.com/38872354/141044975-5f632385-7383-4605-b2ee-4eb4bf890d58.png">


[XS] Navbar ([src/components/Navbar.js](https://github.com/nwplus/livesite/blob/main/src/components/Navbar.js))
- Remove `text-shadow` in [`Navbar > Greeting`](https://github.com/nwplus/livesite/blob/main/src/components/Navbar.js#L39-L41)
- Delete [greetingBorder](https://github.com/nwplus/livesite/blob/main/src/theme/ThemeProvider.js#L114) attribute in ThemeProvider
- Screenshot (navbar visible on /application/part-1, part-2, or part-3): <img width="400" alt="Screen Shot 2021-11-09 at 7 01 17 PM" src="https://user-images.githubusercontent.com/38872354/141041767-0b196f8c-aa29-4608-85f3-2c294888a8e0.png">


[S] Remove nwHacks2021 logo lockup in [src/containers/Landing/index.js](https://github.com/nwplus/livesite/blob/main/src/containers/Landing/index.js#L144)
- Delete logo_lockup image defined at the top of the file
- Delete `StyledLogoLockup`
- Screenshot (on /application/confirmation): <img width="1680" alt="Screen Shot 2021-11-09 at 7 01 59 PM" src="https://user-images.githubusercontent.com/38872354/141041865-79405b5b-20e3-4275-8516-66ba51b7c04d.png">

[S-M] Social media icons 
- These are defined in both [src/containers/Landing/Footer.js](https://github.com/nwplus/livesite/blob/main/src/containers/Landing/Footer.js#L89-L100) and [src/components/ApplicationDashboard.js](https://github.com/nwplus/livesite/blob/main/src/components/ApplicationDashboard.js#L203-L213)
- Pull up the icons into its own component and set the colour of the components to `p.theme.colors.primary`
- In Footer and ApplicationDashboard, reference the new component
- Screenshots (first: /application, second: /application/confirmation):
<img width="1018" alt="Screen Shot 2021-11-09 at 7 35 50 PM" src="https://user-images.githubusercontent.com/38872354/141045287-5ec47810-da44-473a-b502-bac952f63cde.png">
<img width="992" alt="Screen Shot 2021-11-09 at 7 36 28 PM" src="https://user-images.githubusercontent.com/38872354/141045346-bf00e035-364a-4e1c-84f3-a68cf1351f27.png">

**Comment by panjenny0** [comment]
Just created tickets 
- #297 
- #298  
- #299 
updated #292
